### ISSUE TITLE
Question！why are the results so different

### ISSUE THREAD

**Issue by Allan-waker** [nitkannen/CONTRASTE#1]
Thank you very much for the open source code, it's very meaningful work. But I want ask you why are the results so different when I run your code (without any changes)?
Here is my result on laptop14 dataset.
![屏幕截图 2024-01-10 145505](https://github.com/nitkannen/CONTRASTE/assets/64625837/92687b87-0d6c-42e3-b7f7-40c81558a734)
![屏幕截图 2024-01-10 185455](https://github.com/nitkannen/CONTRASTE/assets/64625837/deb38a72-80de-41f8-9a02-0e2d35fbc494)

**Comment by nitkannen** [comment]
Thanks for your comments. I am glad you find our work interesting and would like to experiment with it. Can you please explain the sequence of commands you executed to get the above results?

**Comment by nitkannen** [comment]
Thanks for pointing it out. There was a bug in the previous version of our release. You should be able to reproduce the results now.
