### ISSUE TITLE
What is the function of TCE module? Is it effective?

### ISSUE THREAD

**Issue by Allan-waker** [nitkannen/CONTRASTE#2]
What is the function of TCE module? Is it effective? I feel like the correct number of triples is not predicted well after training? I'm very much looking forward to your answer.

![屏幕截图 2024-01-10 152624](https://github.com/nitkannen/CONTRASTE/assets/64625837/7e1566b3-2768-48a0-a43d-37892ed4ed07)
This is the number of triples predicted by the training process and the correct number of triples. Why are the predicted triples all between 1 and 2?
​

**Comment by nitkannen** [comment]
Thanks for your comments. For an intuitive motivation for the TCE module, please refer to our paper here: https://aclanthology.org/2023.findings-emnlp.807/.

Additionally, there was a bug in the previous version of the release. The TCE module would get trained if the hyperparameters are correctly set up.once again please refer to our paper)
